name: test
on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: install dependencies
        run: npm ci

      - name: build
        run: npm run build
